apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    jenkins.io/chart-release: jenkins-x
    jenkins.io/gitSync: "false"
    jenkins.io/namespace: jx
    jenkins.io/version: "1"
    owner: jatikuma29iv
    provider: github
    repository: environment-minikube-dev
  name: jatikuma29iv-environment-minikube-dev
spec:
  description: Imported application for jatikuma29iv/environment-minikube-dev
  httpCloneURL: https://github.com/jatikuma29iv/environment-minikube-dev.git
  org: jatikuma29iv
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: environment-minikube-dev
  scheduler:
    kind: Scheduler
    name: env-scheduler
  url: https://github.com/jatikuma29iv/environment-minikube-dev.git
